name: bigass metrics
on:
  schedule:
    - cron: "0 12 * * *"
  push:
    branches:
      - master
      - main
  workflow_dispatch:
jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    steps:
      - name: bigass metrics
        uses: lowlighter/metrics@latest
        with:
          # Output
          filename: bigass.svg
          
          # Your GitHub token
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}

          # Options
          user: Coordinate-Cat
          template: classic
          base: header, activity, community, repositories, metadata
          config_display: large
          config_padding: 0, 3%
          config_timezone: Asia/Tokyo
          plugin_people: yes
          plugin_people_types: followers
#           plugin_followup: yes
#           plugin_followup_sections: repositories
          plugin_anilist: yes
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: characters, watching, reading, favorites
          plugin_anilist_limit: 2
          plugin_anilist_shuffle: yes
          plugin_anilist_user: Ocat623
          plugin_anilist_limit_characters: 22
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
#          plugin_habits: yes
#          plugin_habits_facts: no
#          plugin_habits_charts: yes
#          plugin_habits_charts_type: chartist
#           plugin_pagespeed: yes
#           plugin_pagespeed_url: .user.website
#           plugin_isocalendar: yes
#           plugin_isocalendar_duration: half-year
          plugin_lines: yes
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_stars: yes
          plugin_stars_limit: 8

      - name: bottom
        uses: lowlighter/metrics@latest
        with:
          filename: bottom.svg
          token: ${{ secrets.METRICS }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
#           config_order: ""
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
